### Batch Transform on input data with Deployed Model

#### Pulling in best model

In [6]:
import sagemaker
import boto3
from sagemaker import get_execution_role


region = boto3.Session().region_name
session = sagemaker.Session()
le = get_execution_role()

# This is the client we will use to interact with SageMaker AutoPilot
sm = boto3.Session().client(service_name='sagemaker',region_name=region)

# auto_ml_job_name = tuning-job-1-02126272d1024e56bc-178-233ae13b-aws-trial
best_candidate = sm.describe_auto_ml_job(AutoMLJobName='Funders-USA-SEC-data-MVP-1')['BestCandidate']
display(best_candidate)

{'CandidateName': 'tuning-job-1-02126272d1024e56bc-178-233ae13b',
 'FinalAutoMLJobObjectiveMetric': {'MetricName': 'validation:accuracy',
  'Value': 0.5882300138473511},
 'ObjectiveStatus': 'Succeeded',
 'CandidateSteps': [{'CandidateStepType': 'AWS::SageMaker::ProcessingJob',
   'CandidateStepArn': 'arn:aws:sagemaker:us-east-1:570124035543:processing-job/db-1-536cceb09e614d6caa492e76de253c0340dbe419674d48dbb465b7a4b1',
   'CandidateStepName': 'db-1-536cceb09e614d6caa492e76de253c0340dbe419674d48dbb465b7a4b1'},
  {'CandidateStepType': 'AWS::SageMaker::TrainingJob',
   'CandidateStepArn': 'arn:aws:sagemaker:us-east-1:570124035543:training-job/funders-us-dpp0-1-58ce671cb58f43028d8f860f32960e945b9a210e4b8c4',
   'CandidateStepName': 'Funders-US-dpp0-1-58ce671cb58f43028d8f860f32960e945b9a210e4b8c4'},
  {'CandidateStepType': 'AWS::SageMaker::TransformJob',
   'CandidateStepArn': 'arn:aws:sagemaker:us-east-1:570124035543:transform-job/funders-us-dpp0-csv-1-2d7dfb3d81a74ce5bd25436f3683c67639a357334',
   'CandidateStepName': 'Funders-US-dpp0-csv-1-2d7dfb3d81a74ce5bd25436f3683c67639a357334'},
  {'CandidateStepType': 'AWS::SageMaker::TrainingJob',
   'CandidateStepArn': 'arn:aws:sagemaker:us-east-1:570124035543:training-job/tuning-job-1-02126272d1024e56bc-178-233ae13b',
   'CandidateStepName': 'tuning-job-1-02126272d1024e56bc-178-233ae13b'}],
 'CandidateStatus': 'Completed',
 'InferenceContainers': [{'Image': '683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-sklearn-automl:0.2-1-cpu-py3',
   'ModelDataUrl': 's3://sagemaker-us-east-1-570124035543/export-flow-04-21-57-21-dd5ae906/machine-learning-output/autopilot-output/Funders-USA-SEC-data-MVP-1/data-processor-models/Funders-US-dpp0-1-58ce671cb58f43028d8f860f32960e945b9a210e4b8c4/output/model.tar.gz',
   'Environment': {'AUTOML_TRANSFORM_MODE': 'feature-transform',
    'SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT': 'application/x-recordio-protobuf',
    'SAGEMAKER_PROGRAM': 'sagemaker_serve',
    'SAGEMAKER_SUBMIT_DIRECTORY': '/opt/ml/model/code'}},
  {'Image': '683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-xgboost:1.0-1-cpu-py3',
   'ModelDataUrl': 's3://sagemaker-us-east-1-570124035543/export-flow-04-21-57-21-dd5ae906/machine-learning-output/autopilot-output/Funders-USA-SEC-data-MVP-1/tuning/Funders-US-dpp0-xgb/tuning-job-1-02126272d1024e56bc-178-233ae13b/output/model.tar.gz',
   'Environment': {'MAX_CONTENT_LENGTH': '20971520',
    'SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT': 'text/csv',
    'SAGEMAKER_INFERENCE_OUTPUT': 'predicted_label',
    'SAGEMAKER_INFERENCE_SUPPORTED': 'predicted_label,probability,probabilities'}},
  {'Image': '683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-sklearn-automl:0.2-1-cpu-py3',
   'ModelDataUrl': 's3://sagemaker-us-east-1-570124035543/export-flow-04-21-57-21-dd5ae906/machine-learning-output/autopilot-output/Funders-USA-SEC-data-MVP-1/data-processor-models/Funders-US-dpp0-1-58ce671cb58f43028d8f860f32960e945b9a210e4b8c4/output/model.tar.gz',
   'Environment': {'AUTOML_TRANSFORM_MODE': 'inverse-label-transform',
    'SAGEMAKER_DEFAULT_INVOCATIONS_ACCEPT': 'text/csv',
    'SAGEMAKER_INFERENCE_INPUT': 'predicted_label',
    'SAGEMAKER_INFERENCE_OUTPUT': 'predicted_label',
    'SAGEMAKER_INFERENCE_SUPPORTED': 'predicted_label,probability,labels,probabilities',
    'SAGEMAKER_PROGRAM': 'sagemaker_serve',
    'SAGEMAKER_SUBMIT_DIRECTORY': '/opt/ml/model/code'}}],
 'CreationTime': datetime.datetime(2021, 2, 5, 4, 12, 22, tzinfo=tzlocal()),
 'EndTime': datetime.datetime(2021, 2, 5, 4, 13, 11, tzinfo=tzlocal()),
 'LastModifiedTime': datetime.datetime(2021, 2, 5, 4, 29, 31, 702000, tzinfo=tzlocal())}

In [168]:
from sagemaker.predictor import Predictor
from sagemaker.serializers import CSVSerializer
from sagemaker.deserializers import CSVDeserializer
import pandas as pd
import numpy as np


predictor = Predictor(
    endpoint_name='Funders-USA-SEC-data-MVP-1-ep-med1',
    sagemaker_session=session,
    serializer=CSVSerializer(),
    deserializer=CSVDeserializer())

# Load in ground truth dataset
ds_g_truth_path = '/root/Funders-USA-ML-Backend/datasets/datasets_SEC/SEC-MVP-1-Dataset.csv'
df_gt = pd.read_csv(ds_g_truth_path, header=0)
display(df_gt.head(2))
display(len(df_gt))

# Load in dataset with no target column
path = '/root/Funders-USA-ML-Backend/datasets/datasets_SEC/SEC-MVP-1-Dataset-no-target-col.csv'
df_no_tar_col = pd.read_csv(path)
display(df_no_tar_col.head(2))

,Funding_Success,OFFERINGAMOUNT,MAXIMUMOFFERINGAMOUNT,CURRENTEMPLOYEES,TOTALASSETMOSTRECENTFISCALYEAR,TOTALASSETPRIORFISCALYEAR,CASHEQUIMOSTRECENTFISCALYEAR,CASHEQUIPRIORFISCALYEAR,ACTRECEIVEDRECENTFISCALYEAR,ACTRECEIVEDPRIORFISCALYEAR,SHORTTERMDEBTMRECENTFISCALYEAR,SHORTTERMDEBTPRIORFISCALYEAR,LONGTERMDEBTRECENTFISCALYEAR,LONGTERMDEBTPRIORFISCALYEAR,NETINCOMEMOSTRECENTFISCALYEAR,NETINCOMEPRIORFISCALYEAR,Form_C_Number
0,1,275000.0,500000.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,1,400000.0,1000000.0,3,230909.0,441532.0,193376.0,432140.0,-1097.0,0.0,589120.0,569251.0,230909.0,441532.0,-298573.0,-361237.0,1

1702

,OFFERINGAMOUNT,MAXIMUMOFFERINGAMOUNT,CURRENTEMPLOYEES,TOTALASSETMOSTRECENTFISCALYEAR,TOTALASSETPRIORFISCALYEAR,CASHEQUIMOSTRECENTFISCALYEAR,CASHEQUIPRIORFISCALYEAR,ACTRECEIVEDRECENTFISCALYEAR,ACTRECEIVEDPRIORFISCALYEAR,SHORTTERMDEBTMRECENTFISCALYEAR,SHORTTERMDEBTPRIORFISCALYEAR,LONGTERMDEBTRECENTFISCALYEAR,LONGTERMDEBTPRIORFISCALYEAR,NETINCOMEMOSTRECENTFISCALYEAR,NETINCOMEPRIORFISCALYEAR,Form_C_Number
0,275000.0,500000.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,400000.0,1000000.0,3,230909.0,441532.0,193376.0,432140.0,-1097.0,0.0,589120.0,569251.0,230909.0,441532.0,-298573.0,-361237.0,1

In [84]:
# Obtain predictions from SageMaker endpoint
prediction = predictor.predict(df_no_tar_col.to_csv(sep=',', header=None, index=False))

In [85]:
prediction_array = np.array(prediction)
display(prediction_array)
display(prediction_array[:,0])
only_preds = prediction_array[:,0]

array([['0', "['1', '0']", '[0.4528607130050659, 0.5471392869949341]'],
       ['1', "['1', '0']", '[0.6817927956581116, 0.3182072043418884]'],
       ['1', "['1', '0']", '[0.5831929743289948, 0.41680702567100525]'],
       ...,
       ['1', "['1', '0']", '[0.6199167370796204, 0.38008326292037964]'],
       ['1', "['1', '0']", '[0.5245495438575745, 0.47545045614242554]'],
       ['1', "['1', '0']", '[0.6412034630775452, 0.35879653692245483]']],
      dtype='<U41')

array(['0', '1', '1', ..., '1', '1', '1'], dtype='<U41')

In [169]:
# # Load prediction in pandas and compare to ground truth
prediction_df = pd.DataFrame(only_preds)
display(prediction_df.head(2))

df_gt.insert(1,'Prediction', prediction_df)
df_gt = df_gt.astype({'Prediction': int})

   0
0  0
1  1

In [173]:
xdf_gt = df_gt.copy()
display(xdf_gt.head(5))
df_yes_no = xdf_gt['Funding_Success'] == xdf_gt['Prediction']
display(df_yes_no.head(2))
xdf_gt.insert(2,'Correct', df_yes_no)
xdf_gt.loc[xdf_gt.Correct == False, 'Correct'] = 'No'
xdf_gt.loc[xdf_gt.Correct == True, 'Correct'] = 'Yes'
display(xdf_gt.head(5))

,Funding_Success,Prediction,OFFERINGAMOUNT,MAXIMUMOFFERINGAMOUNT,CURRENTEMPLOYEES,TOTALASSETMOSTRECENTFISCALYEAR,TOTALASSETPRIORFISCALYEAR,CASHEQUIMOSTRECENTFISCALYEAR,CASHEQUIPRIORFISCALYEAR,ACTRECEIVEDRECENTFISCALYEAR,ACTRECEIVEDPRIORFISCALYEAR,SHORTTERMDEBTMRECENTFISCALYEAR,SHORTTERMDEBTPRIORFISCALYEAR,LONGTERMDEBTRECENTFISCALYEAR,LONGTERMDEBTPRIORFISCALYEAR,NETINCOMEMOSTRECENTFISCALYEAR,NETINCOMEPRIORFISCALYEAR,Form_C_Number
0,1,0,275000.0,500000.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,1,1,400000.0,1000000.0,3,230909.0,441532.0,193376.0,432140.0,-1097.0,0.0,589120.0,569251.0,230909.0,441532.0,-298573.0,-361237.0,1
2,1,1,50000.0,1000000.0,10,5015954.0,0.0,1250.0,0.0,0.0,0.0,267070.0,0.0,0.0,0.0,-230547.0,0.0,1
3,1,0,250000.0,1000000.0,3,10170.0,7321.0,10170.0,7321.0,0.0,0.0,0.0,0.0,0.0,0.0,-36772.0,-2250.0,1
4,1,0,500000.0,1000000.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

0    False
1     True
dtype: bool

,Funding_Success,Prediction,Correct,OFFERINGAMOUNT,MAXIMUMOFFERINGAMOUNT,CURRENTEMPLOYEES,TOTALASSETMOSTRECENTFISCALYEAR,TOTALASSETPRIORFISCALYEAR,CASHEQUIMOSTRECENTFISCALYEAR,CASHEQUIPRIORFISCALYEAR,ACTRECEIVEDRECENTFISCALYEAR,ACTRECEIVEDPRIORFISCALYEAR,SHORTTERMDEBTMRECENTFISCALYEAR,SHORTTERMDEBTPRIORFISCALYEAR,LONGTERMDEBTRECENTFISCALYEAR,LONGTERMDEBTPRIORFISCALYEAR,NETINCOMEMOSTRECENTFISCALYEAR,NETINCOMEPRIORFISCALYEAR,Form_C_Number
0,1,0,No,275000.0,500000.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,1,1,Yes,400000.0,1000000.0,3,230909.0,441532.0,193376.0,432140.0,-1097.0,0.0,589120.0,569251.0,230909.0,441532.0,-298573.0,-361237.0,1
2,1,1,Yes,50000.0,1000000.0,10,5015954.0,0.0,1250.0,0.0,0.0,0.0,267070.0,0.0,0.0,0.0,-230547.0,0.0,1
3,1,0,No,250000.0,1000000.0,3,10170.0,7321.0,10170.0,7321.0,0.0,0.0,0.0,0.0,0.0,0.0,-36772.0,-2250.0,1
4,1,0,No,500000.0,1000000.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [174]:
display(xdf_gt.head(50))

,Funding_Success,Prediction,Correct,OFFERINGAMOUNT,MAXIMUMOFFERINGAMOUNT,CURRENTEMPLOYEES,TOTALASSETMOSTRECENTFISCALYEAR,TOTALASSETPRIORFISCALYEAR,CASHEQUIMOSTRECENTFISCALYEAR,CASHEQUIPRIORFISCALYEAR,ACTRECEIVEDRECENTFISCALYEAR,ACTRECEIVEDPRIORFISCALYEAR,SHORTTERMDEBTMRECENTFISCALYEAR,SHORTTERMDEBTPRIORFISCALYEAR,LONGTERMDEBTRECENTFISCALYEAR,LONGTERMDEBTPRIORFISCALYEAR,NETINCOMEMOSTRECENTFISCALYEAR,NETINCOMEPRIORFISCALYEAR,Form_C_Number
0,1,0,No,275000.0,500000.0,3,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,1
1,1,1,Yes,400000.0,1000000.0,3,230909.00,441532.00,193376.00,432140.00,-1097.0,0.0,589120.00,569251.00,230909.00,441532.00,-298573.00,-361237.00,1
2,1,1,Yes,50000.0,1000000.0,10,5015954.00,0.00,1250.00,0.00,0.0,0.0,267070.00,0.00,0.00,0.00,-230547.00,0.00,1
3,1,0,No,250000.0,1000000.0,3,10170.00,7321.00,10170.00,7321.00,0.0,0.0,0.00,0.00,0.00,0.00,-36772.00,-2250.00,1
4,1,0,No,500000.0,1000000.0,2,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,1
5,1,1,Yes,99840.0,901888.0,5,1153234.00,694289.00,58131.00,1000.00,0.0,0.0,79397.00,108455.00,0.00,0.00,-1922699.00,-1079379.00,3
6,0,0,Yes,100000.0,1000000.0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,1
7,0,0,Yes,100000.0,1000000.0,0,54008.00,54129.00,2156.00,4414.00,5180.0,0.0,0.00,0.00,87504.00,74269.00,43556.00,87834.00,1
8,0,0,Yes,80000.0,100000.0,2,35873.00,0.00,27303.00,0.00,0.0,0.0,10202.00,0.00,63799.00,0.00,-48127.00,0.00,1
9,1,1,Yes,20000.0,100000.0,2,12461.00,35873.00,3877.00,27303.00,0.0,0.0,0.00,0.00,92150.00,63799.00,-102832.00,-48127.00,2
10,1,1,Yes,22400.0,999880.0,6,26753.00,0.00,2170.00,0.00,0.0,0.0,10041.00,0.00,0.00,0.00,-8288.00,0.00,1
11,0,0,Yes,200000.0,1000000.0,0,88815.00,0.00,12166.00,0.00,11250.0,0.0,10356.00,0.00,32222.00,0.00,-4763.00,0.00,1
12,0,1,No,300000.0,996000.0,0,738636.00,799612.00,6697.00,2432.00,23876.0,24193.0,148073.00,148170.00,464128.00,485244.00,381628.00,326093.00,1
13,1,1,Yes,70000.0,1000000.0,0,738636.00,799612.00,6697.00,2432.00,23876.0,24193.0,148073.00,148170.00,464128.00,485224.00,-381628.00,-326093.00,2
14,0,1,No,60000.0,100000.0,5,105693.00,11664.00,22497.07,1686.11,0.0,0.0,10118.00,2173.00,0.00,0.00,-12796.00,3716.00,1
15,0,0,Yes,300000.0,1000000.0,8,161623.00,73417.00,5993.00,4900.00,0.0,0.0,35611.00,34585.00,670062.00,280643.00,-459638.00,-290958.00,1
16,1,1,Yes,25000.0,100000.0,1,4551918.97,3651353.81,-3286.00,1838.28,375.0,-850.0,15211.20,-91.34,3496391.37,2735860.03,124522.43,-33698.97,1
17,0,0,Yes,50000.0,1000000.0,3,1255.00,0.00,1255.00,0.00,0.0,0.0,0.00,0.00,1255.00,0.00,18745.00,0.00,1
18,1,1,Yes,50000.0,500000.0,3,1255.00,0.00,1255.00,0.00,0.0,0.0,0.00,0.00,1255.00,0.00,-18745.00,0.00,2
19,1,1,Yes,50000.0,100000.0,2,43882.04,48920.10,3007.97,30688.28,0.0,0.0,36260.13,28237.35,94434.51,78342.73,-29152.62,20089.15,1
20,0,0,Yes,50000.0,100000.0,4,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,1
21,1,1,Yes,50000.0,100000.0,12,583711.00,246008.00,383616.00,107231.00,116862.0,57087.0,0.00,0.00,1099957.00,799957.00,-72133.00,-9560.00,1
22,0,1,No,99999.9,999999.0,3,87772.00,0.00,86424.00,0.00,0.0,0.0,341326.00,0.00,0.00,0.00,-253544.00,0.00,1
23,1,1,Yes,50000.0,100000.0,2,138159.00,48801.00,1534.00,1512.00,0.0,0.0,58778.00,64570.00,226418.00,0.00,-144819.00,-51274.00,1
24,0,0,Yes,50000.0,100000.0,6,843125.00,0.00,70337.00,0.00,0.0,0.0,70000.00,0.00,175000.00,0.00,-174663.00,0.00,1
25,0,0,Yes,50000.0,100000.0,5,129599.00,82367.00,9997.00,27942.00,22702.0,10330.0,51400.00,17263.00,252063.00,163560.00,-94908.00,-68563.00,1
26,0,0,Yes,50000.0,1000000.0,5,37516.00,48983.00,0.00,255.00,0.0,0.0,26813.00,32416.00,0.00,0.00,0.00,0.00,1
27,1,1,Yes,20000.0,100000.0,6,127803.00,0.00,0.00,0.00,0.0,0.0,127562.00,0.00,7065.00,0.00,129663.00,0.00,2
28,1,1,Yes,20000.0,100000.0,3,127803.00,0.00,0.00,0.00,0.0,0.0,127562.00,0.00,7065.00,0.00,-129663.00,0.00,1
29,1,1,Yes,100000.0,1000000.0,7,1228213.00,965104.00,200802.00,100811.00,67538.0,97723.0,938684.00,778223.00,316426.00,344994.00,-85411.00,-577998.00,2
30,1,1,Yes,50000.0,100000.0,8,559684.00,0.00,392970.00,0.00,1401.0,0.0,231.00,0.00,559684.00,0.00,-57247.00,0.00,1
31,0,0,Yes,50000.0,388000.0,5,37516.00,48983.00,0.00,255.00,0.0,0.0,26813.00,32416.00,0.00,0.00,-5864.00,-1136818.00,2
32,0,0,Yes,25000.0,100000.0,4,342658.00,446980.00,105271.00,213039.00,0.0,0.0,58872.00,79205.00,577657.00,491548.00,-184589.00,-214102.00,1
33,1,0,No,25000.0,100000.0,4,342658.00,446980.00,105271.00,213039.00,0.0,0.0,58872.00,79205.00,577657.00,491548.00,-184589.00,-214102.00,2
34,1,1,Yes,50000.0,1000000.0,4,335856.00,0.00,132659.00,0.00,0.0,0.0,11597.00,0.00,0.00,0.00,-111841.00,0.00,1
35,0,1,No,50000.0,300000.0,4,335856.00,0.00,132659.00,0.00,0.0,0.0,11597.00,0.00,0.00,0.00,-111841.00,0.00,2
36,1,1,Yes,50000.0,230000.0,5,545040.00,276115.00,37737.00,132659.00,0.0,0.0,66943.00,11597.00,119118.00,0.00,-287317.00,-111841.00,3
37,0,1,No,50000.0,400000.0,6,1288685.00,614554.00,39482.00,37737.00,2572.0,0.0,156598.00,66843.00,782202.00,119118.00,-374640.00,-287317.00,4
38,0,1,No,25000.0,1000000.0,7,86780.00,8606.00,31076.00,5866.00,0.0,0.0,0.00,5866.00,131.00,0.00,-120410.00,-6394.00,1
39,0,1,No,50000.0,1000000.0,2,86780.00,8606.00,31076.00,5866.00,0.0,0.0,0.00,5866.00,131.00,0.00,-120410.00,-6394.00,2
40,0,0,Yes,50000.0,100000.0,1,8100.00,0.00,4000.00,0.00,0.0,0.0,0.00,0.00,12000.00,0.00,-28057.00,0.00,1
41,0,0,Yes,50000.0,1000000.0,2,218410.55,0.00,208960.92,0.00,0.0,0.0,14702.92,0.00,376275.49,0.00,-192650.78,0.00,1
42,1,1,Yes,100000.0,1000000.0,7,1228213.00,965104.00,200802.00,100811.00,67538.0,97723.0,938684.00,778223.00,316426.00,344994.00,-85411.00,-577998.00,1
43,1,1,Yes,10000.0,516663.0,6,110083.00,0.00,41126.00,0.00,31380.0,0.0,582.00,0.00,0.00,0.00,-136911.00,0.00,2
44,0,0,Yes,278066.0,999362.0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,1
45,0,0,Yes,250000.0,1000000.0,2,159506.00,86976.00,92937.00,16560.00,0.0,0.0,306917.00,296745.00,132221.00,118055.00,-261808.00,-288215.00,1
46,0,0,Yes,100000.0,1000000.0,0,54008.00,54129.00,2156.00,4414.00,5180.0,0.0,0.00,0.00,87504.00,74269.00,-43556.00,-87834.00,1
47,0,0,Yes,400000.0,1000000.0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,1
48,0,0,Yes,200000.0,1000000.0,0,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.00,0.00,1
49,0,0,Yes,300000.0,1000000.0,3,2411.00,4178.00,56.00,56.00,0.0,0.0,281029.00,131131.00,0.00,135000.00,-16665.00,-184565.00,1

In [114]:
accuracy = (df_gt.reset_index()['Funding_Success'] == df_gt['Prediction']).sum() / len(df_gt)
print('Accuracy: {}'.format(accuracy))

Accuracy: 0.0