## This notebook merges 5 years of data into one dataframe for preprocessing

### Reusable Functions

In [ ]:
# Reusable Functions for later or future

#### adding text in a list of strings
# dirs_25 = [i + "_25" for i in dirs_]
# print()
# print(dirs_25)


#### Replacing text in a list of strings
#dirs_ = [i.replace("_cf", '') for i in dirs_path]


#### Working example of concat function
# df1 = pd.DataFrame({'rating': [90, 85, 82, 88, 94, 90, 76, 75], 'points': [25, 20, 14, 16, 27, 20, 12, 15]})
# df2 = pd.DataFrame({'assists': [5, 7, 7, 8, 5, 7], 'rebounds': [11, 8, 10, 6, 6, 9]})
# df3 = pd.concat([df1, df2], axis=1)
# display(df3)


#### working example of pandas .append function
# df1 = pd.DataFrame({'rating': [90, 85, 82, 88, 94, 90, 76, 75], 'points': [25, 20, 14, 16, 27, 20, 12, 15]})
# df2 = pd.DataFrame({'rating': [5, 7, 7, 8, 5, 7],'points': [11, 8, 10, 6, 6, 9]})
# df3 = pd.DataFrame()

# df3 = df3.append(df1, ignore_index=True)
# df3 = df3.append(df2, ignore_index=True)
# display(df3)


#### Working code for listing all files in datasets_SEC folder
# dirName = r"C:\Users\ggomp\OneDrive\Documents\GitHub\Funders-USA-ML-Backend\datasets\datasets_SEC"
# listOfFiles = list()
# for (dirpath, dirnames, filenames) in os.walk(dirName):
#     listOfFiles += [os.path.join(dirpath, file) for file in filenames]
# for elem in listOfFiles:
#     print(elem)


#### Working custom code for creating a list of all folder paths
# path = r"C:\Users\ggomp\OneDrive\Documents\GitHub\Funders-USA-ML-Backend\datasets\datasets_SEC"
# path, dirs, files = next(os.walk(path))
# dirs_path = ["{}\\".format(path) + i for i in dirs]
# display(dirs_path)


### working example of putting first item of a list into a variable
# list_example = ["one", "two", "three", "four"]
# for i in list_example:
#     item_1 = i
#     display(item_1)

### General Imports & Pandas Settings

In [1]:
import pandas as pd
import os


# pd.set_option("max_colwidth", 250)
pd.set_option("max_colwidth", 10)
pd.set_option("display.max_columns", 60)
pd.set_option('max_rows', None)

### 1. Loading in 5 years of SEC data

In [4]:
path = r"C:\Users\ggomp\OneDrive\Documents\GitHub\Funders-USA-ML-Backend\datasets\datasets_SEC"
path, dirs, files = next(os.walk(path))
dirs_paths = ["{}\\".format(path) + i for i in dirs]


display(dirs_paths)

StopIteration:

In [4]:
# Working complete loop of excel merging

curr_qt_df = pd.DataFrame()
curr_df = pd.DataFrame()
df = pd.DataFrame()
list_of_docs = ('DISCLOSURE.tsv', 'INFORMATION.tsv', 'SUBMISSION.tsv')

for i in dirs_paths:
    curr_path = i
    #display(curr_path)
    path, dirs, files = next(os.walk(curr_path))
    #display(files)
    files_paths = ["{}\\".format(path) + i for i in files]  
    #display(files_paths)
    for i in files_paths:
        if i.endswith(list_of_docs):
            curr_df = pd.DataFrame()
            curr_df = pd.read_table(i)
            #display(curr_df.head())
            curr_qt_df = pd.concat([curr_df, curr_qt_df], axis=1)
            #print(curr_qt_df.shape)
        #print("if statement complete")
    #print("appending qt_df to df")
    df = df.append(curr_qt_df, ignore_index=True)
    print(df.shape)
    #print("resetting qt_df to empty")
    curr_qt_df = pd.DataFrame()
    #print("exit curr_path")
#print("exit entire loop")
print()
print("Master dataset")
display(df.head(2))

(73, 58)
(223, 58)
(417, 58)
(617, 58)
(996, 58)
(1320, 58)
(1753, 58)
(2162, 58)
(2920, 58)
(3421, 58)
(3911, 58)
(4391, 58)
(5131, 58)
(5615, 58)

Master dataset

,ACCESSION_NUMBER,SUBMISSION_TYPE,FILING_DATE,CIK,FILE_NUMBER,PERIOD,ACCESSION_NUMBER,ISAMENDMENT,PROGRESSUPDATE,NATUREOFAMENDMENT,NAMEOFISSUER,LEGALSTATUSFORM,LEGALSTATUSOTHERDESC,JURISDICTIONORGANIZATION,DATEINCORPORATION,STREET1,STREET2,CITY,STATEORCOUNTRY,ZIPCODE,ISSUERWEBSITE,COMPANYNAME,COMMISSIONCIK,COMMISSIONFILENUMBER,CRDNUMBER,ACCESSION_NUMBER,COMPENSATIONAMOUNT,FINANCIALINTEREST,SECURITYOFFEREDTYPE,SECURITYOFFEREDOTHERDESC,NOOFSECURITYOFFERED,PRICE,PRICEDETERMINATIONMETHOD,OFFERINGAMOUNT,OVERSUBSCRIPTIONACCEPTED,OVERSUBSCRIPTIONALLOCATIONTYPE,DESCOVERSUBSCRIPTION,MAXIMUMOFFERINGAMOUNT,DEADLINEDATE,CURRENTEMPLOYEES,TOTALASSETMOSTRECENTFISCALYEAR,TOTALASSETPRIORFISCALYEAR,CASHEQUIMOSTRECENTFISCALYEAR,CASHEQUIPRIORFISCALYEAR,ACTRECEIVEDRECENTFISCALYEAR,ACTRECEIVEDPRIORFISCALYEAR,SHORTTERMDEBTMRECENTFISCALYEAR,SHORTTERMDEBTPRIORFISCALYEAR,LONGTERMDEBTRECENTFISCALYEAR,LONGTERMDEBTPRIORFISCALYEAR,REVENUEMOSTRECENTFISCALYEAR,REVENUEPRIORFISCALYEAR,COSTGOODSSOLDRECENTFISCALYEAR,COSTGOODSSOLDPRIORFISCALYEAR,TAXPAIDMOSTRECENTFISCALYEAR,TAXPAIDPRIORFISCALYEAR,NETINCOMEMOSTRECENTFISCALYEAR,NETINCOMEPRIORFISCALYEAR
0,000167...,C/A,20160628,1676570,020-22902,NaN,000167...,0,NaN,Offeri...,SharkS...,Corpor...,NaN,DE,2016-0...,1 MEAD...,NaN,HUNTIN...,NY,11746,www.sh...,FLASHF...,1320303.0,008-66859,134742.0,000167...,FlashF...,NaN,Prefer...,NaN,140000.0,0.5,NaN,70000.0,Y,Other,At the...,100000.0,2016-1...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-19304.0,-3919.0
1,000167...,C,20160628,1676480,020-22903,NaN,000167...,0,NaN,NaN,Brewer...,Limite...,NaN,TX,2016-0...,4715 E...,NaN,AUSTIN,TX,78702,caskan...,NextSe...,1667892.0,007-00023,283225.0,000167...,NextSe...,None,Debt,NaN,NaN,NaN,The va...,250000.0,Y,First-...,NaN,300000.0,2016-0...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 2. Merging all 5 years of data into one dataframe

In [4]:

list_of_docs = ('DISCLOSURE.tsv', 'INFORMATION.tsv', 'SUBMISSION.tsv')
curr_qt_df = pd.DataFrame()
curr_df = pd.DataFrame()
df = pd.DataFrame()


for i in dirs_paths:
    curr_path = i
    path, dirs, files = next(os.walk(curr_path))
    files_paths = ["{}\\".format(path) + i for i in files] 
    
    for i in files_paths:
        if i.endswith(list_of_docs):
            curr_df = pd.DataFrame()
            curr_df = pd.read_table(i)
            curr_qt_df = pd.concat([curr_df, curr_qt_df], axis=1)
            
    df = df.append(curr_qt_df, ignore_index=True)
    print(df.shape)
    curr_qt_df = pd.DataFrame()

(73, 58)
(223, 58)
(417, 58)
(617, 58)
(996, 58)
(1320, 58)
(1753, 58)
(2162, 58)
(2920, 58)
(3421, 58)
(3911, 58)
(4391, 58)
(5131, 58)
(5615, 58)

Master dataset

,ACCESSION_NUMBER,SUBMISSION_TYPE,FILING_DATE,CIK,FILE_NUMBER,PERIOD,ACCESSION_NUMBER,ISAMENDMENT,PROGRESSUPDATE,NATUREOFAMENDMENT,NAMEOFISSUER,LEGALSTATUSFORM,LEGALSTATUSOTHERDESC,JURISDICTIONORGANIZATION,DATEINCORPORATION,STREET1,STREET2,CITY,STATEORCOUNTRY,ZIPCODE,ISSUERWEBSITE,COMPANYNAME,COMMISSIONCIK,COMMISSIONFILENUMBER,CRDNUMBER,ACCESSION_NUMBER,COMPENSATIONAMOUNT,FINANCIALINTEREST,SECURITYOFFEREDTYPE,SECURITYOFFEREDOTHERDESC,NOOFSECURITYOFFERED,PRICE,PRICEDETERMINATIONMETHOD,OFFERINGAMOUNT,OVERSUBSCRIPTIONACCEPTED,OVERSUBSCRIPTIONALLOCATIONTYPE,DESCOVERSUBSCRIPTION,MAXIMUMOFFERINGAMOUNT,DEADLINEDATE,CURRENTEMPLOYEES,TOTALASSETMOSTRECENTFISCALYEAR,TOTALASSETPRIORFISCALYEAR,CASHEQUIMOSTRECENTFISCALYEAR,CASHEQUIPRIORFISCALYEAR,ACTRECEIVEDRECENTFISCALYEAR,ACTRECEIVEDPRIORFISCALYEAR,SHORTTERMDEBTMRECENTFISCALYEAR,SHORTTERMDEBTPRIORFISCALYEAR,LONGTERMDEBTRECENTFISCALYEAR,LONGTERMDEBTPRIORFISCALYEAR,REVENUEMOSTRECENTFISCALYEAR,REVENUEPRIORFISCALYEAR,COSTGOODSSOLDRECENTFISCALYEAR,COSTGOODSSOLDPRIORFISCALYEAR,TAXPAIDMOSTRECENTFISCALYEAR,TAXPAIDPRIORFISCALYEAR,NETINCOMEMOSTRECENTFISCALYEAR,NETINCOMEPRIORFISCALYEAR
0,000167...,C/A,20160628,1676570,020-22902,NaN,000167...,0,NaN,Offeri...,SharkS...,Corpor...,NaN,DE,2016-0...,1 MEAD...,NaN,HUNTIN...,NY,11746,www.sh...,FLASHF...,1320303.0,008-66859,134742.0,000167...,FlashF...,NaN,Prefer...,NaN,140000.0,0.5,NaN,70000.0,Y,Other,At the...,100000.0,2016-1...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-19304.0,-3919.0
1,000167...,C,20160628,1676480,020-22903,NaN,000167...,0,NaN,NaN,Brewer...,Limite...,NaN,TX,2016-0...,4715 E...,NaN,AUSTIN,TX,78702,caskan...,NextSe...,1667892.0,007-00023,283225.0,000167...,NextSe...,None,Debt,NaN,NaN,NaN,The va...,250000.0,Y,First-...,NaN,300000.0,2016-0...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 3. Displaying "master" dataframe

In [ ]:

print()
print("Master dataset")
display(df.head(20))

### 4. Creating "master" excel File

In [5]:

path = r"C:\Users\ggomp\OneDrive\Documents\GitHub\Funders-USA-ML-Backend\datasets\datasets_SEC\Aggregated SEC including 2019Q3 and before.xlsx"
df.to_excel(path, index=False, header=True)